<table border="0" style="background:#eee; color:#333; border:solid 1px #000000; width:800px;">
  <tr>
    <td colspan="2"><strong>Заявка на скидку 40%</strong></td>
  </tr>
  <tr>
    <td>%%name.title%%</td>
    <td>%%name.value%%</td>
  </tr>
  <tr>
    <td>%%tell.title%%</td>
    <td>%%tell.value%%</td>
  </tr>
  <tr>
    <td>%%e-mail.title%%</td>
    <td>%%e-mail.value%%</td>
  </tr>
  <tr>
    <td>skype</td>
    <td>%%skype.value%%</td>
  </tr>
  <tr>
    <td>%%city.title%%</td>
    <td>%%city.value%%</td>
  </tr>
  <tr>
    <td><b>Реффер</b></td>
    <td>%%where.value%%</td>
  </tr>
</table>
